version: '3.8'

services:

  database:
    image: "postgres:16"
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zookeeper
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    container_name: zookeeper
    restart: always

    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zookeeper

    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    name: app-network
    driver: bridge


# TODO
#- add healthcheck
