version: '3.8'

services:

  postgres:
    logging:
      driver: journald

    image: "postgres:16"

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zookeeper
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

  app:
    logging:
      driver: journald

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zookeeper

    restart: always

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    links:
      - postgres:postgres